name: flutter_translate
description: Flutter Translate is a fully featured localization / internationalization (i18n) library for Flutter.
version: 4.1.1
homepage: https://jesway.com
repository: https://github.com/Jesway/flutter_translate

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  universal_io: ^2.3.1
  intl: ">=0.19.0 <0.21.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: